### ISSUE TITLE
Does it work with Kafka 3.6?

### ISSUE THREAD

**Issue by dancb10** [scylladb/scylla-cdc-source-connector#75]
Tried updating de debezium and kafka version to make it compatible with Kafka 3.6.x but there a re lot of things broken. Is there a plan to make it compatible with the this Kafka version?

**Comment by dkropachev** [comment]
We are currently working on it.

**Comment by dancb10** [comment]
Is there an estimated ETA for the release?

**Comment by dkropachev** [comment]
> Is there an estimated ETA for the release?

16 of Jun.

**Comment by dancb10** [comment]
Awesome, thank you!

**Comment by Sh4d1** [comment]
Hello! Any news on that? Thanks!

**Comment by Bouncheck** [comment]
Have you tried running 1.2.4 or 1.2.3? I was able to launch 1.2.4 with confluent 8.0.0 and some earlier versions, so Kafka 3.6 should be supported.

**Comment by dkropachev** [comment]
> image: localhost:32000/kafka-connect:1.0.7

Where this image comes from ?

**Comment by Bouncheck** [comment]
> > image: localhost:32000/kafka-connect:1.0.7
> 
> Where this image comes from ?

@dancb10 I'm also suspecting this as the cause.
When you look at this exception chain it leads to `java.lang.NoSuchMethodException: org.apache.kafka.connect.json.JsonConverter.convertToConnect`
The connect-api jars are not something bundled with the connector. Usually they are already included with the Kafka Connect setup.
If your images misses them, then adding them should fix this issue.

**Comment by dancb10** [comment]
it seems that building the cdc scylla connector and some of its dependencies is still not compatible with kafka3.6x. Since this method is bundled in the Kafka version but the cdc overrides with its dependencies. Was the connector ported to 3.6 as initially asked in this issue?
This file confirms the root cause of the java.lang.NoSuchMethodError: 'java.util.Map org.apache.kafka.common.utils.ConfigUtils.translateDeprecatedConfigs(java.util.Map, java.lang.String[][])' error you're encountering when running the Scylla CDC connector with Kafka Connect 4.0.0. The issue stems from a version mismatch in the Kafka libraries, specifically because the pom.xml declares a dependency on org.apache.kafka:connect-transforms:3.9.1 and org.apache.kafka:connect-api:3.9.1, while your Kafka Connect runtime is version 4.0.0. The translateDeprecatedConfigs method, required by connect-transforms-4.0.0.jar (used in the ReplaceField transformation), was introduced in Kafka 3.6.0 and is present in Kafka 4.0.0, but the older kafka-clients-3.9.1.jar (a transitive dependency of connect-transforms:3.9.1) is likely being loaded at runtime, causing the NoSuchMethodError.

**Comment by dancb10** [comment]
Ok, tried bumping 
```
        <debezium.version>3.0.8.Final</debezium.version>
        <!-- Docs claim java 8 supported, but support is deprecated -->
        <kafka.version>4.0.0</kafka.version>
```

But then I get a bunch of errors 
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.14.1:compile (default-compile) on project scylla-cdc-source-connector: Compilation failure: Compilation failure:
[ERROR] /Users/danpopescu/git/scylla-cdc-source-connector/src/main/java/com/scylladb/cdc/debezium/connector/ScyllaOffsetContext.java:[15,8] com.scylladb.cdc.debezium.connector.ScyllaOffsetContext is not abstract and does not override abstract method preSnapshotStart(boolean) in io.debezium.pipeline.spi.OffsetContext
[ERROR] /Users/danpopescu/git/scylla-cdc-source-connector/src/main/java/com/scylladb/cdc/debezium/connector/ScyllaOffsetContext.java:[61,3] method does not override or implement a method from a supertype
[ERROR] /Users/danpopescu/git/scylla-cdc-source-connector/src/main/java/com/scylladb/cdc/debezium/connector/ScyllaOffsetContext.java:[69,3] method does not override or implement a method from a supertype
[ERROR] /Users/danpopescu/git/scylla-cdc-source-connector/src/main/java/com/scylladb/cdc/debezium/connector/ScyllaTaskContext.java:[19,27] incompatible types: java.lang.String cannot be converted to io.debezium.config.CommonConnectorConfig
[ERROR] /Users/danpopescu/git/scylla-cdc-source-connector/src/main/java/com/scylladb/cdc/debezium/connector/TaskStateOffsetContext.java:[13,8] com.scylladb.cdc.debezium.connector.TaskStateOffsetContext is not abstract and does not override abstract method preSnapshotStart(boolean) in io.debezium.pipeline.spi.OffsetContext
[ERROR] /Users/danpopescu/git/scylla-cdc-source-connector/src/main/java/com/scylladb/cdc/debezium/connector/TaskStateOffsetContext.java:[45,3] method does not override or implement a method from a supertype
[ERROR] /Users/danpopescu/git/scylla-cdc-source-connector/src/main/java/com/scylladb/cdc/debezium/connector/TaskStateOffsetContext.java:[53,3] method does not override or implement a method from a supertype
```

So I guess it was never released based on this comment? 
```

[dkropachev](https://github.com/dkropachev)
[on Jun 18](https://github.com/scylladb/scylla-cdc-source-connector/issues/75#issuecomment-2983711038)
Collaborator
Hello! Any news on that? Thanks!

Keep working on it, unfortunately it takes longer we expected, I will update you when it is done
```

**Comment by Bouncheck** [comment]
@dancb10 we run integration tests with various recent Kafka versions, including both Apache Kafka 4.0.0 and Confluent Platform 7.6.6 (which corresponds to Apache Kafka 3.6.x) and we are not observing such issues.
For those tests we use the .zip package under `target/components/packages`.
I have some issues building it locally right now. You should be able to obtain one from
https://www.confluent.io/hub/scylladb/scylla-cdc-source-connector
Simply download the zip and unzip that into the same location you had jar with dependencies in. Remove the jar with dependencies too or it will conflict.

>it seems that building the cdc scylla connector and some of its dependencies is still not compatible with kafka3.6x. Since this method is bundled in the Kafka version but the cdc overrides with its dependencies. Was the connector ported to 3.6 as initially asked in this issue?

It seems that fat-jar (jar with dependencies) can introduce conflicts when it comes to Kafka dependencies in contrast to the zip package. I'll investigate whether that should be happening.

>This file confirms the root cause of the java.lang.NoSuchMethodError: 'java.util.Map org.apache.kafka.common.utils.ConfigUtils.translateDeprecatedConfigs(java.util.Map, java.lang.String[][])' error you're encountering when running the Scylla CDC connector with Kafka Connect 4.0.0. The issue stems from a version mismatch in the Kafka libraries, specifically because the pom.xml declares a dependency on org.apache.kafka:connect-transforms:3.9.1 and org.apache.kafka:connect-api:3.9.1, while your Kafka Connect runtime is version 4.0.0. The translateDeprecatedConfigs method, required by connect-transforms-4.0.0.jar (used in the ReplaceField transformation), was introduced in Kafka 3.6.0 and is present in Kafka 4.0.0, but the older kafka-clients-3.9.1.jar (a transitive dependency of connect-transforms:3.9.1) is likely being loaded at runtime, causing the NoSuchMethodError.

The versions do not make sense to me here. If something was introduced in 3.6.0 and is still present in 4.0.0 there should not be an issue with using 3.9.1 which is between them. 
Also it looks like `translateDeprecatedConfigs` was removed in 4.0.0:
https://github.com/apache/kafka/commit/b3b86d52f4255ef7f6efad83209e3abbc19421e7
The stacktrace you've provided seems to use `connect-transforms-4.0.0.jar` since it's mentioned there in square brackets. 
```
java.lang.NoSuchMethodError: 'java.util.Map org.apache.kafka.common.utils.ConfigUtils.translateDeprecatedConfigs(java.util.Map, java.lang.String[][])'
	at org.apache.kafka.connect.transforms.ReplaceField.configure(ReplaceField.java:101) ~[connect-transforms-4.0.0.jar:?]
	at org.apache.kafka.connect.runtime.ConnectorConfig.transformationStages(ConnectorConfig.java:316) ~[connect-runtime-4.0.0.jar:?]
```
I don't understand why would it try to use missing API in such case.

Anyway, try the package from the Confluent hub and let us know if it helped for now.

**Comment by dancb10** [comment]
Hello, it did worked indeed after putting the zip file will all dependencies instead of the fat jar. Apparently if you put that it has dependencies that override the Kafka libraries. So everything works now, thank you!
